spring:
  r2dbc:
   url: r2dbc:pool:mysql://localhost:3306/data_feeds
   username: root
   password: 123456
  flyway:
    url: jdbc:mysql://localhost:3306/data_feeds
    schemas: data_feeds
    user: "root"
    password: "123456"
